// код для генерации
// protoc -I shared `
//   --go_out=shared/pkg --go_opt=paths=source_relative `
//   --go-grpc_out=shared/pkg --go-grpc_opt=paths=source_relative `
//   shared/proto/sign/v1/sign.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/sign/v1/sign.proto

package signV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------------
// Сообщение SignRequest
// ----------------------------
// Описывает данные, которые клиент отправляет для подписи документа.
type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      []byte                 `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`           // сам документ в виде массива байт
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // идентификатор пользователя (Gateway проверяет JWT)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_proto_sign_v1_sign_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sign_v1_sign_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_proto_sign_v1_sign_proto_rawDescGZIP(), []int{0}
}

func (x *SignRequest) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *SignRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ----------------------------
// Сообщение SignResponse
// ----------------------------
// Описывает ответ сервиса после подписи документа
type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`                     // криптографическая подпись документа
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"` // уникальный идентификатор документа для хранения или дальнейшей проверки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_proto_sign_v1_sign_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sign_v1_sign_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_proto_sign_v1_sign_proto_rawDescGZIP(), []int{1}
}

func (x *SignResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

var File_proto_sign_v1_sign_proto protoreflect.FileDescriptor

const file_proto_sign_v1_sign_proto_rawDesc = "" +
	"\n" +
	"\x18proto/sign/v1/sign.proto\x12\asign.v1\"B\n" +
	"\vSignRequest\x12\x1a\n" +
	"\bdocument\x18\x01 \x01(\fR\bdocument\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"M\n" +
	"\fSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId2J\n" +
	"\vSignService\x12;\n" +
	"\fSignDocument\x12\x14.sign.v1.SignRequest\x1a\x15.sign.v1.SignResponseBEZCgithub.com/KolManis/signing-project/shared/pkg/proto/sign/v1;signV1b\x06proto3"

var (
	file_proto_sign_v1_sign_proto_rawDescOnce sync.Once
	file_proto_sign_v1_sign_proto_rawDescData []byte
)

func file_proto_sign_v1_sign_proto_rawDescGZIP() []byte {
	file_proto_sign_v1_sign_proto_rawDescOnce.Do(func() {
		file_proto_sign_v1_sign_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sign_v1_sign_proto_rawDesc), len(file_proto_sign_v1_sign_proto_rawDesc)))
	})
	return file_proto_sign_v1_sign_proto_rawDescData
}

var file_proto_sign_v1_sign_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sign_v1_sign_proto_goTypes = []any{
	(*SignRequest)(nil),  // 0: sign.v1.SignRequest
	(*SignResponse)(nil), // 1: sign.v1.SignResponse
}
var file_proto_sign_v1_sign_proto_depIdxs = []int32{
	0, // 0: sign.v1.SignService.SignDocument:input_type -> sign.v1.SignRequest
	1, // 1: sign.v1.SignService.SignDocument:output_type -> sign.v1.SignResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sign_v1_sign_proto_init() }
func file_proto_sign_v1_sign_proto_init() {
	if File_proto_sign_v1_sign_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sign_v1_sign_proto_rawDesc), len(file_proto_sign_v1_sign_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sign_v1_sign_proto_goTypes,
		DependencyIndexes: file_proto_sign_v1_sign_proto_depIdxs,
		MessageInfos:      file_proto_sign_v1_sign_proto_msgTypes,
	}.Build()
	File_proto_sign_v1_sign_proto = out.File
	file_proto_sign_v1_sign_proto_goTypes = nil
	file_proto_sign_v1_sign_proto_depIdxs = nil
}
